/**
 * 在线沙箱 (StackBlitz / CodeSandbox / CodePen) 一键调起工具
 * 零第三方 UI 库依赖，原生运行 react-public-components
 */

export interface SandboxConfig {
	title?: string;
	description?: string;
	dependencies?: Record<string, string>;
	devDependencies?: Record<string, string>;
}

const defaultPackageJson = (
	dependencies: Record<string, string> = {},
	devDependencies: Record<string, string> = {},
) => ({
	name: 'react-public-components-demo',
	version: '1.0.0',
	description: 'Interactive demo generated by react-public-components',
	main: 'src/index.tsx',
	dependencies: {
		react: '^18.3.1',
		'react-dom': '^18.3.1',
		'react-public-components': 'latest',
		...dependencies,
	},
	devDependencies: {
		'@types/react': '^18.3.3',
		'@types/react-dom': '^18.3.0',
		typescript: '^5.5.0',
		...devDependencies,
	},
});

const defaultHtml = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>React Public Components Demo</title>
  <link rel="stylesheet" href="https://unpkg.com/react-public-components/dist/index.css" />
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; padding: 24px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background: #f8fafc; }
  </style>
</head>
<body>
  <div id="root"></div>
</body>
</html>`;

const defaultIndexTsx = `import React from 'react';
import { createRoot } from 'react-dom/client';
import 'react-public-components/dist/index.css';
import App from './App';

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>
  );
}`;

/**
 * 在 StackBlitz 中打开项目（极速、免注册、支持完整 TSX 编译）
 */
export function openInStackBlitz(code: string, config: SandboxConfig = {}) {
	const form = document.createElement('form');
	form.method = 'POST';
	form.action = 'https://stackblitz.com/run';
	form.target = '_blank';
	form.style.display = 'none';

	const pkg = defaultPackageJson(config.dependencies, config.devDependencies);

	const fields: Record<string, string> = {
		'project[title]': config.title || 'react-public-components Demo',
		'project[description]': config.description || 'Live Component Demo',
		'project[template]': 'create-react-app',
		'project[files][package.json]': JSON.stringify(pkg, null, 2),
		'project[files][public/index.html]': defaultHtml,
		'project[files][src/index.tsx]': defaultIndexTsx,
		'project[files][src/App.tsx]': code,
		'project[files][tsconfig.json]': JSON.stringify(
			{
				compilerOptions: {
					target: 'es5',
					lib: ['dom', 'dom.iterable', 'esnext'],
					allowJs: true,
					skipLibCheck: true,
					esModuleInterop: true,
					allowSyntheticDefaultImports: true,
					strict: true,
					forceConsistentCasingInFileNames: true,
					noFallthroughCasesInSwitch: true,
					module: 'esnext',
					moduleResolution: 'node',
					resolveJsonModule: true,
					isolatedModules: true,
					noEmit: true,
					jsx: 'react-jsx',
				},
				include: ['src'],
			},
			null,
			2,
		),
	};

	Object.entries(fields).forEach(([key, val]) => {
		const input = document.createElement('input');
		input.type = 'hidden';
		input.name = key;
		input.value = val;
		form.appendChild(input);
	});

	document.body.appendChild(form);
	form.submit();
	document.body.removeChild(form);
}

/**
 * 在 CodeSandbox 中打开项目
 */
export function openInCodeSandbox(code: string, config: SandboxConfig = {}) {
	const pkg = defaultPackageJson(config.dependencies, config.devDependencies);

	const files = {
		'package.json': {
			content: JSON.stringify(pkg, null, 2),
		},
		'public/index.html': {
			content: defaultHtml,
		},
		'src/index.tsx': {
			content: defaultIndexTsx,
		},
		'src/App.tsx': {
			content: code,
		},
	};

	fetch('https://codesandbox.io/api/v1/sandboxes/define?json=1', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
			Accept: 'application/json',
		},
		body: JSON.stringify({ files }),
	})
		.then((res) => res.json())
		.then((data) => {
			if (data && data.sandbox_id) {
				window.open(`https://codesandbox.io/s/${data.sandbox_id}`, '_blank');
			}
		})
		.catch(() => {
			// 降级使用 StackBlitz 打开
			openInStackBlitz(code, config);
		});
}

/**
 * 在 CodePen 中打开演练场
 */
export function openInCodePen(code: string, config: SandboxConfig = {}) {
	const form = document.createElement('form');
	form.method = 'POST';
	form.action = 'https://codepen.io/pen/define/';
	form.target = '_blank';
	form.style.display = 'none';

	let cleanJs = code
		.replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?/g, '')
		.replace(/export\s+default\s+App;?/g, '')
		.replace(/export\s+default\s+/g, '');

	cleanJs +=
		'\n\nconst root = ReactDOM.createRoot(document.getElementById("root"));\nroot.render(<App />);';

	const data = {
		title: config.title || 'react-public-components Demo',
		description: config.description || 'Live Component Demo',
		html: '<div id="root"></div>',
		js: cleanJs,
		js_pre_processor: 'babel',
		css: 'body { margin: 0; padding: 24px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f8fafc; }',
		js_external: [
			'https://unpkg.com/react@18/umd/react.production.min.js',
			'https://unpkg.com/react-dom@18/umd/react-dom.production.min.js',
			'https://unpkg.com/react-public-components/dist/index.umd.js',
		].join(';'),
		css_external: ['https://unpkg.com/react-public-components/dist/index.css'].join(';'),
	};

	const input = document.createElement('input');
	input.type = 'hidden';
	input.name = 'data';
	input.value = JSON.stringify(data);
	form.appendChild(input);

	document.body.appendChild(form);
	form.submit();
	document.body.removeChild(form);
}

/**
 * 在新标签页中独立打开运行
 */
export function openInNewTab(code: string, title: string = 'Demo Preview') {
	const newWin = window.open('', '_blank');
	if (!newWin) return;

	const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <link rel="stylesheet" href="https://unpkg.com/react-public-components/dist/index.css" />
  <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; padding: 24px; background: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
    #root { background: #fff; padding: 32px; border-radius: 12px; box-shadow: 0 4px 16px rgba(0,0,0,0.06); max-width: 900px; margin: 0 auto; }
  </style>
</head>
<body>
  <div id="root"></div>
  <script type="text/babel">
    const { useState, useEffect, useRef, useMemo, useCallback } = React;
    
    ${code
			.replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?/g, '')
			.replace(/export\s+default\s+App;?/g, '')
			.replace(/export\s+default\s+/g, '')}

    if (typeof App !== 'undefined') {
      const root = ReactDOM.createRoot(document.getElementById('root'));
      root.render(<App />);
    }
  </script>
</body>
</html>`;

	newWin.document.open();
	newWin.document.write(htmlContent);
	newWin.document.close();
}
